export interface DataLayerGA4AttrType {
    event?: string | string | "NA",
	eventName?: string | "NA",
	data_label?: string | "NA",
	data_label2?: string | "NA",
	cpe_parent_subject?: string | "NA",
	cpe_child_subject?: string | "NA",
	page_name?: string | "NA",
	college_name?: string | "NA",
	provider_type?: string | "NA",
	course_name?: string | "NA",
	sponsored_sr?: string | "NA",
	college_id?: string | "NA",
	ucas_points?: string | "NA",
	study_mode?: string | "NA",
	target_year?: string | "NA",
	clearing?: string | "NA",
	user_id?: string | "NA",
	study_level?: string | "NA",
	article_category?: string | "NA",
	destination_country?: string | "NA",
	data_label3?: string | "NA",
	data_label4?: string | "NA",
	data_label5?: string | "NA",
	cta_name?: string | "NA",
	cta_url?: string | "NA",
	website_name?: string | "NA",
	contentful_1?: string | "NA",
	contentful_2?: string | "NA",

}