import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@packages/shared-components/common-utilities/header/headercomponents";
const farroBold = localFont({
  src: "./fonts/Farro-Bold.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const interBold = localFont({
  src: "./fonts/Inter-Bold.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${farroBold.variable} ${interBold.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
