import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@packages/shared-components/common-utilities/header/headercomponents";
import Footer from "@packages/shared-components/common-utilities/footer/footercomponents";
import Script from "next/script";
import OneTrustCookie from "./OneTrustcookie";
const farroBold = localFont({
  src: "./fonts/Farro-Bold.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const interBold = localFont({
  src: "./fonts/Inter-Bold.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${farroBold.variable} ${interBold.variable} antialiased`}
      >
        <Script src="https://cdn-apac.onetrust.com/scripttemplates/otSDKStub.js" id="oneTrustCookieeId" data-domain-script="aef8a843-4acf-4f91-acd1-f823a4a625c0" />
        <OneTrustCookie />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
