import { v4 as uuidv4 } from "uuid";
const makeApiCall = async (
  url: string,
  method: string,
  headers: Record<string, string> | null,
  queryParams: string | null,
  bodyjson: any
): Promise<any> => {
  const apiUrl = `${process.env.NEXT_PUBLIC_BFF_API_DOMAIN}/hewebsites/v1/${url}${
    queryParams ? `?${queryParams}` : ""
  }`;
  try {
    const response = await fetch(apiUrl, {
      method: method.toUpperCase(),
      headers: {
        "Content-Type": "application/json",
        "x-correlation-id": uuidv4(),
        "x-api-key": `${process.env.NEXT_PUBLIC_X_API_KEY}`,
        ...headers,
      },
      body: method === "GET" ? undefined : JSON.stringify(bodyjson),
    });

    if (!response.ok) {
      const errorResponse = await response.json().catch(() => ({}));
      console.error({
        error: errorResponse,
        endpoint: apiUrl,
        status: response?.status,
        statusText: response?.statusText,
      });
      throw new Error(`API Error: ${response?.status} ${response?.statusText}`);
    }

    return await response.json();
  } catch (error: unknown) {
    if (error instanceof Error) {
      console.error(`API call failed: ${error.message}`, { endpoint: apiUrl });
      throw error;
    } else {
      console.error("Unknown error occurred", { endpoint: apiUrl, error });
      throw new Error("An unknown error occurred during the API call.");
    }
  }
};

const dt = {
  qualificationList: [
    { qualCode: "M", qualTextKey: "degree", qualDisplayDesc: "Undergraduate" },
  ],
  studyModeList: [
    { studyModeDesc: "Full time", studyModeTextKey: "full-time" },
  ],
  studyMethodList: null,
  regionList: [
    {
      regionId: 1,
      regionName: "UK",
      regionTextKey: "uk",
      parentRegionId: null,
    },
    {
      regionId: 2,
      regionName: "England",
      regionTextKey: "england",
      parentRegionId: 1,
    },
    {
      regionId: 18,
      regionName: "West Midlands",
      regionTextKey: "west-midlands",
      parentRegionId: 2,
    },
  ],
  uniLocationTypeList: [{ locTypeDesc: "Seaside", locTypeTextKey: "seaside" }],
  universityGroupList: [
    { universityGroupDesc: "Russel Group", universityGroupTextKey: "RG" },
  ],
  cityList: [{ cityName: "Birmingham", cityTextKey: "birmingham" }],
  intakeYearDetails: {
    intakeYearList: [{ year: 2025 }],
    intakeMonthList: [{ month: "Feb" }, { month: "Apr" }],
  },
  subjectFilterList: [
    {
      categoryCode: "AK.61",
      categoryDesc: "AAT Association of Accounting Technicians",
      parentSubject: "Accounting, Business & Finance",
      subjectTextKey: "aat-association-of-accounting-technicians",
      qualificationCode: "M",
    },
    {
      categoryCode: "AK.65",
      categoryDesc: "ACCA Association of Chartered Certified Accountants",
      parentSubject: "Accounting, Business & Finance",
      subjectTextKey: "acca-association-of-chartered-certified-accountants",
      qualificationCode: "M",
    },
    {
      categoryCode: "AK.6",
      categoryDesc: "Accountancy",
      parentSubject: "Accounting, Business & Finance",
      subjectTextKey: "accountancy",
      qualificationCode: "M",
    },
    {
      categoryCode: "AK.",
      categoryDesc: "Accounting",
      parentSubject: "Accounting, Business & Finance",
      subjectTextKey: "accounting",
      qualificationCode: "M",
    },
    {
      categoryCode: "AK.,A,AK.2",
      categoryDesc: "Accounting, Business & Finance",
      parentSubject: null,
      subjectTextKey: "accounting-business-finance",
      qualificationCode: "M",
    },
    {
      categoryCode: "PS.21",
      categoryDesc: "Addiction Counselling",
      parentSubject: "Psychology and Counselling",
      subjectTextKey: "addiction-counselling",
      qualificationCode: "M",
    },
    {
      categoryCode: "PS.22",
      categoryDesc: "Bereavement Counselling",
      parentSubject: "Psychology and Counselling",
      subjectTextKey: "bereavement-counselling",
      qualificationCode: "M",
    },
    {
      categoryCode: "A",
      categoryDesc: "Business Studies",
      parentSubject: "Accounting, Business & Finance",
      subjectTextKey: "business-studies",
      qualificationCode: "M",
    },
    {
      categoryCode: "C",
      categoryDesc: "Computing & IT",
      parentSubject: null,
      subjectTextKey: "computing-it",
      qualificationCode: "M",
    },
    {
      categoryCode: "P,PB.",
      categoryDesc: "Health and Medicine",
      parentSubject: null,
      subjectTextKey: "health-and-medicine",
      qualificationCode: "M",
    },
    {
      categoryCode: "P",
      categoryDesc: "Healthcare Science",
      parentSubject: "Health and Medicine",
      subjectTextKey: "healthcare-science",
      qualificationCode: "M",
    },
  ],
  universityFilterList: [
    {
      collegeId: 337954,
      collegeNameDisplay: "A3 TEST",
      collegeNameAlias: "A3 TEST",
      collegeName: "A3 TEST",
      collegeTextKey: "a3-test",
    },
    {
      collegeId: 143355,
      collegeNameDisplay: "AccentSoftening",
      collegeNameAlias: "AccentSoftening",
      collegeName: "ACCENT SOFTENING LIMITED",
      collegeTextKey: "accent-softening-limited",
    },
    {
      collegeId: 470804,
      collegeNameDisplay: "ACM (The Academy of Contemporary Music)",
      collegeNameAlias: "ACM (The Academy of Contemporary Music)",
      collegeName: "MY UNIVERSITY_THARANI",
      collegeTextKey: "my-university-tharani",
    },
    {
      collegeId: 466338,
      collegeNameDisplay: "Alpha Test Provider",
      collegeNameAlias: "Alpha Test Provider",
      collegeName: "ALPHA TEST PROVIDER",
      collegeTextKey: "alpha-test-provider",
    },
    {
      collegeId: 469910,
      collegeNameDisplay: "AP institute",
      collegeNameAlias: "AP institute",
      collegeName: "AP INSTITUTE",
      collegeTextKey: "ap-institute",
    },
    {
      collegeId: 472584,
      collegeNameDisplay: "ARU COLLEGE - CAMBRIDGE CAMPUS",
      collegeNameAlias: "ARU COLLEGE - CAMBRIDGE CAMPUS",
      collegeName: "ARU COLLEGE - CAMBRIDGE CAMPUS",
      collegeTextKey: "aru-college-cambridge-campus",
    },
    {
      collegeId: 472746,
      collegeNameDisplay: "Arunn Test provider",
      collegeNameAlias: "Arunn Test provider",
      collegeName: "SAI EU UK",
      collegeTextKey: "sai-eu-uk",
    },
    {
      collegeId: 475424,
      collegeNameDisplay: "AWS Karthick University",
      collegeNameAlias: "AWS Karthick University",
      collegeName: "AWS KARTHICK UNIVERSITY",
      collegeTextKey: "aws-karthick-university",
    },
    {
      collegeId: 473012,
      collegeNameDisplay: "balaji uk university",
      collegeNameAlias: "balaji uk university",
      collegeName: "BALAJI UK UNIVERSITY",
      collegeTextKey: "balaji-uk-university",
    },
    {
      collegeId: 476344,
      collegeNameDisplay: "Deepak_Test_UK",
      collegeNameAlias: "Deepak_Test_UK",
      collegeName: "DEEPAK_TEST_UK",
      collegeTextKey: "deepak-test-uk",
    },
    {
      collegeId: 466282,
      collegeNameDisplay: "DMU",
      collegeNameAlias: "Rin University of London",
      collegeName: "RIN UNIVERSITY OF LONDON",
      collegeTextKey: "rin-university-of-london",
    },
    {
      collegeId: 473584,
      collegeNameDisplay: "EFL mahi",
      collegeNameAlias: "EFL mahi",
      collegeName: "EFL MAHI",
      collegeTextKey: "efl-mahi",
    },
    {
      collegeId: 466780,
      collegeNameDisplay: "fazz",
      collegeNameAlias: "fazz",
      collegeName: "TEST JAN20 3",
      collegeTextKey: "test-jan20-3",
    },
    {
      collegeId: 469948,
      collegeNameDisplay: "Goutham Analytics Test University",
      collegeNameAlias: "Goutham Analytics Test University",
      collegeName: "GOUTHAM ANALYTICS TEST UNIVERSITY",
      collegeTextKey: "goutham-analytics-test-university",
    },
    {
      collegeId: 466270,
      collegeNameDisplay: "Hybrid University",
      collegeNameAlias: "Hybrid University",
      collegeName: "HYBRID UNIVERSITY",
      collegeTextKey: "hybrid-university",
    },
    {
      collegeId: 466036,
      collegeNameDisplay: "Jeevitha UK Test",
      collegeNameAlias: "Jeevitha UK Test",
      collegeName: "JEEVITHA UK TEST",
      collegeTextKey: "jeevitha-uk-test",
    },
    {
      collegeId: 466056,
      collegeNameDisplay: "Jeevitha UK Test 01",
      collegeNameAlias: "Jeevitha UK Test 01",
      collegeName: "JEEVITHA UK TEST 01",
      collegeTextKey: "jeevitha-uk-test-01",
    },
    {
      collegeId: 469666,
      collegeNameDisplay: "Jeswin_UK_KT_testprovider",
      collegeNameAlias: "Jeswin_UK_KT_testprovider",
      collegeName: "JESWIN_UK TEST PROVIDER",
      collegeTextKey: "jeswin-uk-test-provider",
    },
    {
      collegeId: 469704,
      collegeNameDisplay: "Jeswin_UK Test Provider",
      collegeNameAlias: "Jeswin_UK Test Provider",
      collegeName: "JESWIN_UK TEST PROVIDER",
      collegeTextKey: "jeswin-uk-test-provider",
    },
    {
      collegeId: 316892,
      collegeNameDisplay: "Judy Bentinck Millinery",
      collegeNameAlias: "Judy Bentinck Millinery",
      collegeName: "JUDY BENTINCK MILLINERY",
      collegeTextKey: "judy-bentinck-millinery",
    },
    {
      collegeId: 130318,
      collegeNameDisplay: "Kb Kickboxing",
      collegeNameAlias: "Kb Kickboxing",
      collegeName: "KB KICKBOXING",
      collegeTextKey: "kb-kickboxing",
    },
    {
      collegeId: 472550,
      collegeNameDisplay: "Keele University International College - Navitas UK",
      collegeNameAlias: "Keele University International College - Navitas UK",
      collegeName: "KEELE UNIVERSITY INTERNATIONAL COLLEGE - NAVITAS UK",
      collegeTextKey: "keele-university-international-college-navitas-uk",
    },
    {
      collegeId: 132095,
      collegeNameDisplay: "king's college london",
      collegeNameAlias: "KINGS COLLEGE LONDON",
      collegeName: "KCL",
      collegeTextKey: "kcl",
    },
    {
      collegeId: 471664,
      collegeNameDisplay: "mahalakshmi test provider",
      collegeNameAlias: "mahalakshmi test provider",
      collegeName: "MAHALAKSHMI TEST PROVIDER",
      collegeTextKey: "mahalakshmi-test-provider",
    },
    {
      collegeId: 471672,
      collegeNameDisplay: "MahaTest UK",
      collegeNameAlias: "MahaTest UK",
      collegeName: "MAHATEST UK",
      collegeTextKey: "mahatest-uk",
    },
    {
      collegeId: 479894,
      collegeNameDisplay: "Maheswari_test_uk",
      collegeNameAlias: "Maheswari_test_uk",
      collegeName: "MAHESWARI_TEST_UK",
      collegeTextKey: "maheswari-test-uk",
    },
    {
      collegeId: 474074,
      collegeNameDisplay: "mahi_Test1",
      collegeNameAlias: "mahi_Test1",
      collegeName: "MAHI_TEST1",
      collegeTextKey: "mahi-test1",
    },
    {
      collegeId: 472494,
      collegeNameDisplay: "My Study BC Provider",
      collegeNameAlias: "My Study BC Provider",
      collegeName: "MY STUDY BC PROVIDER",
      collegeTextKey: "my-study-bc-provider",
    },
    {
      collegeId: 465898,
      collegeNameDisplay: "naveenuktest",
      collegeNameAlias: "naveenuktest",
      collegeName: "NAVEENUKTEST",
      collegeTextKey: "naveenuktest",
    },
    {
      collegeId: 465948,
      collegeNameDisplay: "naveenuktest1",
      collegeNameAlias: "naveenuktest1",
      collegeName: "NAVEENUKTEST1",
      collegeTextKey: "naveenuktest1",
    },
    {
      collegeId: 469914,
      collegeNameDisplay: "Naveen_UKtest Provider",
      collegeNameAlias: "Naveen_UKtest Provider",
      collegeName: "NAVEEN_UKTEST PROVIDER",
      collegeTextKey: "naveen-uktest-provider",
    },
    {
      collegeId: 470184,
      collegeNameDisplay: "NAVEEN UNIVERSITY UK",
      collegeNameAlias: "NAVEEN UNIVERSITY UK",
      collegeName: "NAVEEN UNIVERSITY UK",
      collegeTextKey: "naveen-university-uk",
    },
    {
      collegeId: 120264,
      collegeNameDisplay: "Ppi Business Nlp",
      collegeNameAlias: "Ppi Business Nlp",
      collegeName: "PPI BUSINESS NLP LTD",
      collegeTextKey: "ppi-business-nlp-ltd",
    },
    {
      collegeId: 471832,
      collegeNameDisplay: "QA practice institution - 1",
      collegeNameAlias: "QA practice institution - 1",
      collegeName: "QA PRACTICE INSTITUTION - 1",
      collegeTextKey: "qa-practice-institution-1",
    },
    {
      collegeId: 471864,
      collegeNameDisplay: "QA practice institution - 2",
      collegeNameAlias: "QA practice institution - 2",
      collegeName: "QA PRACTICE INSTITUTION - 2",
      collegeTextKey: "qa-practice-institution-2",
    },
    {
      collegeId: 464852,
      collegeNameDisplay: "Ramesh Test Provider_UK",
      collegeNameAlias: "Ramesh Test Provider_UK",
      collegeName: "RAMESH TEST UK PROVIDER",
      collegeTextKey: "ramesh-test-uk-provider",
    },
    {
      collegeId: 469912,
      collegeNameDisplay: "RasheedUKPROVIDER",
      collegeNameAlias: "RasheedUKPROVIDER",
      collegeName: "RASHEED_UK_PROVIDER",
      collegeTextKey: "rasheed-uk-provider",
    },
    {
      collegeId: 467012,
      collegeNameDisplay: "Rowan Atkinson University",
      collegeNameAlias: "Rowan Atkinson University",
      collegeName: "ROWAN ATKINSON UNIVERSITY",
      collegeTextKey: "rowan-atkinson-university",
    },
    {
      collegeId: 472704,
      collegeNameDisplay: "Sai Test provider",
      collegeNameAlias: "Sai Test provider",
      collegeName: "SAI TEST PROVIDER",
      collegeTextKey: "sai-test-provider",
    },
    {
      collegeId: 466302,
      collegeNameDisplay: "Saravanantest_uk",
      collegeNameAlias: "Saravanantest_uk",
      collegeName: "TEST ADVERTS",
      collegeTextKey: "test-adverts",
    },
    {
      collegeId: 470086,
      collegeNameDisplay: "saro uk",
      collegeNameAlias: "saro uk",
      collegeName: "SARO UK",
      collegeTextKey: "saro-uk",
    },
    {
      collegeId: 467736,
      collegeNameDisplay: "ShruthiUK2-TestUniv",
      collegeNameAlias: "ShruthiUK2-TestUniv",
      collegeName: "SHRUTHIUK2-TESTUNIV",
      collegeTextKey: "shruthiuk2-testuniv",
    },
    {
      collegeId: 466740,
      collegeNameDisplay: "smart provider",
      collegeNameAlias: "smart provider",
      collegeName: "SMART PROVIDER",
      collegeTextKey: "smart-provider",
    },
    {
      collegeId: 471608,
      collegeNameDisplay: "Srmuniversity4",
      collegeNameAlias: "Srmuniversity4",
      collegeName: "SRMUNIVERSITY4",
      collegeTextKey: "srmuniversity4",
    },
    {
      collegeId: 471610,
      collegeNameDisplay: "Srmuniversity5",
      collegeNameAlias: "Srmuniversity5",
      collegeName: "SRMUNIVERSITY5",
      collegeTextKey: "srmuniversity5",
    },
    {
      collegeId: 471612,
      collegeNameDisplay: "Srmuniversity6",
      collegeNameAlias: "Srmuniversity6",
      collegeName: "SRMUNIVERSITY6",
      collegeTextKey: "srmuniversity6",
    },
    {
      collegeId: 466744,
      collegeNameDisplay: "Surya_uk test provider",
      collegeNameAlias: "Surya_uk test provider",
      collegeName: "TESTING8 PROVIDER",
      collegeTextKey: "testing8-provider",
    },
    {
      collegeId: 466742,
      collegeNameDisplay: "test7",
      collegeNameAlias: "test7",
      collegeName: "TEST7",
      collegeTextKey: "test7",
    },
    {
      collegeId: 466746,
      collegeNameDisplay: "test9 provider",
      collegeNameAlias: "test9 provider",
      collegeName: "TEST9 PROVIDER",
      collegeTextKey: "test9-provider",
    },
    {
      collegeId: 466212,
      collegeNameDisplay: "Test College for KT",
      collegeNameAlias: "Test College for KT",
      collegeName: "TEST COLLEGE FOR KT",
      collegeTextKey: "test-college-for-kt",
    },
    {
      collegeId: 469016,
      collegeNameDisplay: "Test For App",
      collegeNameAlias: "Test For App",
      collegeName: "TEST FOR APP",
      collegeTextKey: "test-for-app",
    },
    {
      collegeId: 466762,
      collegeNameDisplay: "test jan19",
      collegeNameAlias: "test jan19",
      collegeName: "TEST JAN19",
      collegeTextKey: "test-jan19",
    },
    {
      collegeId: 466776,
      collegeNameDisplay: "test jan20 1",
      collegeNameAlias: "test jan20 1",
      collegeName: "TEST JAN20 1",
      collegeTextKey: "test-jan20-1",
    },
    {
      collegeId: 466778,
      collegeNameDisplay: "test jan20 2",
      collegeNameAlias: "test jan20 2",
      collegeName: "TEST JAN20 2",
      collegeTextKey: "test-jan20-2",
    },
    {
      collegeId: 466694,
      collegeNameDisplay: "Test KT Provider",
      collegeNameAlias: "Test KT Provider",
      collegeName: "TEST KT PROVIDER",
      collegeTextKey: "test-kt-provider",
    },
    {
      collegeId: 471828,
      collegeNameDisplay: "Test KT Provider Dec 22",
      collegeNameAlias: "Test KT Provider Dec 22",
      collegeName: "TEST KT PROVIDER DEC 22",
      collegeTextKey: "test-kt-provider-dec-22",
    },
    {
      collegeId: 465092,
      collegeNameDisplay: "TEST OIP PROVIDER",
      collegeNameAlias: "TEST OIP PROVIDER",
      collegeName: "TEST OIP PROVIDER",
      collegeTextKey: "test-oip-provider",
    },
    {
      collegeId: 465506,
      collegeNameDisplay: "Test Practice",
      collegeNameAlias: "Test Practice",
      collegeName: "TEST PRACTICE",
      collegeTextKey: "test-practice",
    },
    {
      collegeId: 466692,
      collegeNameDisplay: "test provider - sugumar",
      collegeNameAlias: "test provider - sugumar",
      collegeName: "TEST PROVIDER - SUGUMAR",
      collegeTextKey: "test-provider-sugumar",
    },
    {
      collegeId: 466972,
      collegeNameDisplay: "Test Provider UK - Feb_07",
      collegeNameAlias: "Test Provider UK - Feb_07",
      collegeName: "TEST PROVIDER UK - FEB_07",
      collegeTextKey: "test-provider-uk-feb-07",
    },
    {
      collegeId: 466492,
      collegeNameDisplay: "Test provider UK - S",
      collegeNameAlias: "Test provider UK - S",
      collegeName: "TEST PROVIDER UK - S",
      collegeTextKey: "test-provider-uk-s",
    },
    {
      collegeId: 472392,
      collegeNameDisplay: "Test Provider - UK Task-1",
      collegeNameAlias: "Test Provider - UK Task-1",
      collegeName: "TEST PROVIDER - UK TASK-1",
      collegeTextKey: "test-provider-uk-task-1",
    },
    {
      collegeId: 370016,
      collegeNameDisplay: "TEST REGRESSION UK",
      collegeNameAlias: "TEST REGRESSION UK",
      collegeName: "TEST REGRESSION UK",
      collegeTextKey: "test-regression-uk",
    },
    {
      collegeId: 466606,
      collegeNameDisplay: "Test UK Institute",
      collegeNameAlias: "Test UK Institute",
      collegeName: "TEST UK INSTITUTE",
      collegeTextKey: "test-uk-institute",
    },
    {
      collegeId: 466616,
      collegeNameDisplay: "Test UK Institute 1",
      collegeNameAlias: "Test UK Institute 1",
      collegeName: "TEST UK INSTITUTE 1",
      collegeTextKey: "test-uk-institute-1",
    },
    {
      collegeId: 466618,
      collegeNameDisplay: "Test UK Institute 2",
      collegeNameAlias: "Test UK Institute 2",
      collegeName: "TEST UK INSTITUTE 2",
      collegeTextKey: "test-uk-institute-2",
    },
    {
      collegeId: 466620,
      collegeNameDisplay: "Test UK Institute 3",
      collegeNameAlias: "Test UK Institute 3",
      collegeName: "TEST UK INSTITUTE 3",
      collegeTextKey: "test-uk-institute-3",
    },
    {
      collegeId: 465504,
      collegeNameDisplay: "Test Uni Domestic",
      collegeNameAlias: "Test Uni Domestic",
      collegeName: "TEST UNI DOMESTIC",
      collegeTextKey: "test-uni-domestic",
    },
    {
      collegeId: 465862,
      collegeNameDisplay: "Test University for KT",
      collegeNameAlias: "Test University for KT",
      collegeName: "TEST UNIVERSITY FOR KT",
      collegeTextKey: "test-university-for-kt",
    },
    {
      collegeId: 466612,
      collegeNameDisplay: "Test University UK - P",
      collegeNameAlias: "Test University UK - P",
      collegeName: "TEST UNIVERSITY UK - P",
      collegeTextKey: "test-university-uk-p",
    },
    {
      collegeId: 466332,
      collegeNameDisplay: "The Best University",
      collegeNameAlias: "The Best University",
      collegeName: "THE BEST UNIVERSITY",
      collegeTextKey: "the-best-university",
    },
    {
      collegeId: 474304,
      collegeNameDisplay: "The Legend",
      collegeNameAlias: "The Legend",
      collegeName: "LEGEND",
      collegeTextKey: "legend",
    },
    {
      collegeId: 339488,
      collegeNameDisplay: "UK Courses",
      collegeNameAlias: "UK Courses",
      collegeName: "UK COURSES",
      collegeTextKey: "uk-courses",
    },
    {
      collegeId: 472372,
      collegeNameDisplay: "Umatestuk Provider",
      collegeNameAlias: "Umatestuk Provider",
      collegeName: "UMATESTUK PROVIDER",
      collegeTextKey: "umatestuk-provider",
    },
    {
      collegeId: 466300,
      collegeNameDisplay: "University of Adverts",
      collegeNameAlias: "University of Adverts",
      collegeName: "UNIVERSITY OF ADVERTS",
      collegeTextKey: "university-of-adverts",
    },
    {
      collegeId: 466216,
      collegeNameDisplay: "University of Business",
      collegeNameAlias: "University of Business",
      collegeName: "UNIVERSITY OF BUSINESS",
      collegeTextKey: "university-of-business",
    },
    {
      collegeId: 470386,
      collegeNameDisplay: "university of central lancashire",
      collegeNameAlias: "UCL",
      collegeName: "university of central lancashire",
      collegeTextKey: "university-of-central-lancashire",
    },
    {
      collegeId: 466258,
      collegeNameDisplay: "University of Excellence",
      collegeNameAlias: "University of Excellence",
      collegeName: "UNIVERSITY OF EXCELLENCE",
      collegeTextKey: "university-of-excellence",
    },
    {
      collegeId: 3747,
      collegeNameDisplay: "University of Lincoln",
      collegeNameAlias: "University of Lincoln",
      collegeName: "UNIVERSITY OF LINCOLN",
      collegeTextKey: "university-of-lincoln",
    },
    {
      collegeId: 465906,
      collegeNameDisplay: "Vahitest01",
      collegeNameAlias: "Vahitest01",
      collegeName: "VAHITEST01",
      collegeTextKey: "vahitest01",
    },
    {
      collegeId: 472826,
      collegeNameDisplay: "vidhya kt provider",
      collegeNameAlias: "vidhya kt provider",
      collegeName: "VIDHYA KT PROVIDER",
      collegeTextKey: "vidhya-kt-provider",
    },
    {
      collegeId: 473386,
      collegeNameDisplay: "vidhya new UK provider",
      collegeNameAlias: "vidhya new UK provider",
      collegeName: "VIDHYA NEW UK PROVIDER",
      collegeTextKey: "vidhya-new-uk-provider",
    },
    {
      collegeId: 473066,
      collegeNameDisplay: "Vidhya UK Country provider",
      collegeNameAlias: "Vidhya UK Country provider",
      collegeName: "VIDHYA UK COUNTRY PROVIDER",
      collegeTextKey: "vidhya-uk-country-provider",
    },
    {
      collegeId: 472832,
      collegeNameDisplay: "Vidhya UKProvider",
      collegeNameAlias: "Vidhya UKProvider",
      collegeName: "VIDHYA UKPROVIDER",
      collegeTextKey: "vidhya-ukprovider",
    },
    {
      collegeId: 127061,
      collegeNameDisplay: "Yacht And Powercraft Design Services Ltd",
      collegeNameAlias: "Yacht And Powercraft Design Services Ltd",
      collegeName: "YACHT AND POWERCRAFT DESIGN SERVICES LTD",
      collegeTextKey: "yacht-and-powercraft-design-services-ltd",
    },
    {
      collegeId: 132171,
      collegeNameDisplay: "Yarborough School",
      collegeNameAlias: "Yarborough School",
      collegeName: "YARBOROUGH SCHOOL",
      collegeTextKey: "yarborough-school",
    },
    {
      collegeId: 467268,
      collegeNameDisplay: "zabi -test provider",
      collegeNameAlias: "zabi -test provider",
      collegeName: "ZABI -TEST PROVIDER",
      collegeTextKey: "zabi-test-provider",
    },
    {
      collegeId: 129887,
      collegeNameDisplay: "Zebra Uno Ltd",
      collegeNameAlias: "Zebra Uno Ltd",
      collegeName: "ZEBRA UNO LTD",
      collegeTextKey: "zebra-uno-ltd",
    },
    {
      collegeId: 467654,
      collegeNameDisplay: null,
      collegeNameAlias: "Test institution - S",
      collegeName: "TEST INSTITUTION - S",
      collegeTextKey: "test-institution-s",
    },
    {
      collegeId: 467656,
      collegeNameDisplay: null,
      collegeNameAlias: "Shruthi's university -1",
      collegeName: "SHRUTHI'S UNIVERSITY -1",
      collegeTextKey: "shruthis-university-1",
    },
    {
      collegeId: 467776,
      collegeNameDisplay: null,
      collegeNameAlias: "ShruthiUK4-TestUniv",
      collegeName: "SHRUTHIUK4-TESTUNIV",
      collegeTextKey: "shruthiuk4-testuniv",
    },
    {
      collegeId: 467814,
      collegeNameDisplay: null,
      collegeNameAlias: "ShruthiUK5-TestUniv",
      collegeName: "SHRUTHIUK5-TESTUNIV",
      collegeTextKey: "shruthiuk5-testuniv",
    },
    {
      collegeId: 474384,
      collegeNameDisplay: null,
      collegeNameAlias: "Stel Andre School of Music",
      collegeName: "STEL ANDRE SCHOOL OF MUSIC",
      collegeTextKey: "stel-andre-school-of-music",
    },
    {
      collegeId: 468932,
      collegeNameDisplay: null,
      collegeNameAlias: "LAMDA",
      collegeName: "LAMDA",
      collegeTextKey: "lamda",
    },
    {
      collegeId: 467134,
      collegeNameDisplay: null,
      collegeNameAlias: "upendar",
      collegeName: "UPENDAR",
      collegeTextKey: "upendar",
    },
    {
      collegeId: 467494,
      collegeNameDisplay: null,
      collegeNameAlias: "Test$ british council",
      collegeName: "TEST BRITISH COUNCIL",
      collegeTextKey: "test-british-council",
    },
  ],
};

const getSrFilter = async (bodyjson: any): Promise<any> => {
  const apiUrl = `${process.env.NEXT_PUBLIC_DOMSERVICE_API_DOMAIN}/dom-search/v1/search/getSearchFilters`;
  try {
    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-correlation-id": uuidv4(),
        sitecode: `${process.env.SITE_CODE}`,
        "x-api-key": `${process.env.NEXT_PUBLIC_DOMSERVICE_X_API_KEY}`,
      },
      body: JSON.stringify(bodyjson),
    });
    if (!response.ok) {
      const errorResponse = await response.json().catch(() => ({}));
      console.error({
        error: errorResponse,
        endpoint: apiUrl,
        status: response?.status,
        statusText: response?.statusText,
      });
      return dt;
    }
    return await response.json();
  } catch (error: unknown) {
    console.error(`API call failed: ${error}`, { endpoint: apiUrl });
    console.error("Unknown error occurred", { endpoint: apiUrl, error });
  }
};

export default makeApiCall;
export { getSrFilter };
