const subjectGuideEventData = {
  event: "subject_guide_events",
  "event name": "sg_subject_opted",
  data_label: "NA",
  data_label2: "NA",
  cpe_parent_subject: "art",
  cpe_child_subject: "NA",
  page_name: "subjectguidelandingpage.jsp",
  college_name: "NA",
  provider_type: "NA",
  course_name: "NA",
  sponsored_sr: "NA",
  college_id: "NA",
  ucas_points: "NA",
  study_mode: "NA",
  target_year: "NA",
  clearing: "in_year",
  wu_user_id: "0",
  study_level: "NA",
  article_category: "NA",
  destination_country: "NA",
  data_label3: "NA",
  data_label4: "NA",
  data_label5: "NA",
};

export { subjectGuideEventData };
